language: node_js
node_js:
- '10'

before_script:
- npm install -g gatsby-cli
script:
- npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local_dir: public
  keep-history: true
  name: "Travis Deploy"
  target_branch: master
  on:
    branch: source
